const express = require('express');
const router = express.Router();
const Group = require('../models/Group');
const Message = require('../models/Message');
const User = require('../models/User');
const Chat = require('../models/Chat');
const mongoose = require('mongoose');
const axios = require('axios');

// In-memory pin store (replace with DB in production)
const pinnedChats = {};

// Debug endpoint to check database contents
router.get('/debug', async (req, res) => {
  try {
    const { userId } = req.query;
    const totalMessages = await Message.countDocuments();
    const totalUsers = await User.countDocuments();
    const sampleMessages = await Message.find({}).limit(5);
    const sampleUsers = await User.find({}).limit(5);
    
    let userMessages = [];
    if (userId) {
      // Only check chat field if userId is a valid ObjectId (for IMS users)
      if (mongoose.Types.ObjectId.isValid(userId)) {
        userMessages = await Message.find({
          $or: [
            { 'sender.id': userId },
            { chat: userId }
          ]
        }).limit(10);
      } else {
        // For students (registration numbers), only check sender.id
        userMessages = await Message.find({
          'sender.id': userId
        }).limit(10);
      }
    }
    
    // Debug: Check messages involving Hargun specifically
    const hargunMessages = await Message.find({
      $or: [
        { 'sender.name': 'Hargun' },
        { 'senderName': 'Hargun' }
      ]
    }).limit(5);
    
    res.json({
      totalMessages,
      totalUsers,
      sampleMessages: sampleMessages.map(m => ({
        _id: m._id,
        sender: m.sender,
        chat: m.chat,
        chatModel: m.chatModel,
        content: m.content,
        createdAt: m.createdAt
      })),
      sampleUsers: sampleUsers.map(u => ({ _id: u._id, name: u.name, email: u.email })),
      userMessages: userMessages.map(m => ({
        _id: m._id,
        sender: m.sender,
        chat: m.chat,
        chatModel: m.chatModel,
        content: m.content,
        createdAt: m.createdAt
      })),
      hargunMessages: hargunMessages.map(m => ({
        _id: m._id,
        sender: m.sender,
        chat: m.chat,
        chatModel: m.chatModel,
        content: m.content,
        createdAt: m.createdAt
      }))
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get chat list (for user) - Using Chat model
router.get('/', async (req, res) => {
  try {
    const { userId } = req.query;
    console.log('=== CHAT API CALLED (NEW VERSION) ===');
    console.log('Chat API: Request received for userId:', userId);
    if (!userId) return res.status(400).json({ error: 'userId required' });

    // Get chats from Chat model where user is a participant
    // Check both as string and ObjectId for student compatibility
    // Only try ObjectId conversion if userId looks like a valid ObjectId
    const isValidObjectId = mongoose.Types.ObjectId.isValid(userId) && userId.length === 24;
    const chats = await Chat.find({
      $or: [
        { participants: userId },
        ...(isValidObjectId ? [{ participants: new mongoose.Types.ObjectId(userId) }] : [])
      ]
    }).sort({ lastMessageTime: -1 });
    
    console.log(`Chat API: Found ${chats.length} chats for user ${userId}`);
    console.log(`Chat API: UserId type: ${typeof userId}, length: ${userId.length}, isValidObjectId: ${isValidObjectId}`);
    console.log(`Chat API: Query used:`, { $or: [{ participants: userId }, ...(isValidObjectId ? [{ participants: new mongoose.Types.ObjectId(userId) }] : [])] });
    console.log('Chat API: Raw chats from database:', chats.map(c => ({ _id: c._id, participants: c.participants, lastMessage: c.lastMessage })));
    
    // Process chats to include user details
    const processedChats = [];
    const seenChats = new Set(); // Track processed chats to avoid duplicates
    
    for (const chat of chats) {
      if (chat.is_group) {
        // Group chat
        const group = await Group.findById(chat.chat_id);
        if (group) {
          processedChats.push({
            _id: chat.chat_id,
            name: chat.group_name || group.name,
            avatar: chat.group_icon || '/assets/images/group-avatar.png',
            isGroup: true,
            lastMessage: chat.lastMessage || '',
            time: chat.lastMessageTime ? chat.lastMessageTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '',
            unread: 0,
          pinned: false,
            status: 'Active',
            members: chat.participants || [],
            admins: group.admins || [],
            isAutoGenerated: group.isAutoGenerated || false,
            moduleInfo: group.moduleInfo || null,
            groupType: group.groupType || 'batch'
          });
        }
      } else {
        // Individual chat - find the other participant
        const otherParticipantId = chat.participants.find(p => p.toString() !== userId.toString());
        console.log(`Chat API: Processing individual chat - participants: ${chat.participants}, userId: ${userId}, otherParticipantId: ${otherParticipantId}`);
        
        // Create a unique key for this chat to avoid duplicates
        const chatKey = `${userId}-${otherParticipantId}`;
        const reverseChatKey = `${otherParticipantId}-${userId}`;
        
        if (seenChats.has(chatKey) || seenChats.has(reverseChatKey)) {
          console.log(`Chat API: Skipping duplicate chat: ${chatKey}`);
          continue;
        }
        
        if (otherParticipantId) {
          // Try to find user in IMS User collection
          let otherUser = await User.findById(otherParticipantId);
          console.log(`Chat API: Looking up user ${otherParticipantId} in IMS User collection:`, otherUser ? `Found: ${otherUser.name}` : 'Not found');
          
          if (!otherUser) {
            // If not found in IMS, might be a student - try to get from LMS API
            console.log(`Chat API: User not found in IMS, trying LMS API for: ${otherParticipantId}`);
            try {
              // Try to fetch student data from external LMS API
              console.log(`Chat API: Fetching student data from LMS API for: ${otherParticipantId}`);
              
              // Try to fetch from LMS API
              const response = await axios.get(`https://lms.ifda.in/api/v1/students`, {
                params: {
                  id: otherParticipantId,
                  registration_number: otherParticipantId
                },
                timeout: 5000 // 5 second timeout
              });
              
              if (response.data && response.data.length > 0) {
                const student = response.data[0];
                otherUser = {
                  _id: otherParticipantId,
                  name: student.name || student.fullName || student.student_name || `Student ${otherParticipantId}`,
                  email: student.email || '',
                  thumb: student.profile_image || '/assets/images/user-avatar.png'
                };
                console.log(`Chat API: Found student in LMS API: ${otherUser.name}`);
          } else {
                // Fallback to generic name
                otherUser = {
                  _id: otherParticipantId,
                  name: `User ${otherParticipantId}`,
                  email: '',
                  thumb: '/assets/images/user-avatar.png'
                };
                console.log(`Chat API: No student found in LMS API, using fallback name: ${otherUser.name}`);
              }
            } catch (error) {
              console.log('Chat API: Error fetching student data:', error.message);
              // Fallback to generic name
              otherUser = {
                _id: otherParticipantId,
                name: `User ${otherParticipantId}`,
                email: '',
                thumb: '/assets/images/user-avatar.png'
              };
              console.log(`Chat API: Error occurred, using fallback name: ${otherUser.name}`);
            }
          } else {
            console.log(`Chat API: Found IMS user: ${otherUser.name}`);
          }
          
          processedChats.push({
            _id: otherParticipantId,
            name: otherUser.name || 'Unknown User',
            avatar: otherUser.thumb || '/assets/images/user-avatar.png',
            isGroup: false,
            lastMessage: chat.lastMessage || '',
            time: chat.lastMessageTime ? chat.lastMessageTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '',
            unread: 0,
            pinned: false,
            status: 'Active',
            email: otherUser.email || ''
          });
          console.log(`Chat API: Added chat for ${otherUser.name} (${otherParticipantId})`);
          
          // Mark this chat as seen to avoid duplicates
          seenChats.add(chatKey);
          seenChats.add(reverseChatKey);
        }
      }
    }
    
    console.log(`Chat API: Returning ${processedChats.length} processed chats`);
    console.log('Chat API: Final processed chats:', processedChats.map(c => ({ name: c.name, _id: c._id, lastMessage: c.lastMessage })));
    res.json(processedChats);
  } catch (err) {
    console.error('Chat API: Error occurred:', err);
    console.error('Chat API: Error stack:', err.stack);
    res.status(500).json({ error: err.message });
  }
});

// Pin/Unpin chat
router.post('/:id/pin', async (req, res) => {
  try {
    const { userId, pin } = req.body; // pin: true/false
    if (!userId) return res.status(400).json({ error: 'userId required' });
    pinnedChats[req.params.id] = pin ? userId : undefined;
    res.json({ chatId: req.params.id, pinned: !!pin });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
