const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const GroupSchema = new Schema({
  name: { type: String, required: true },
  image: { type: String }, // S3 URL or path
  description: { type: String },
  members: [{ 
    type: Schema.Types.Mixed, // Can be ObjectId (IMS users) or String (LMS student IDs)
    ref: 'User' 
  }],
  admins: [{ 
    type: Schema.Types.Mixed, // Can be ObjectId (IMS users) or String (LMS student IDs)
    ref: 'User' 
  }],
  createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  isAutoGenerated: { type: Boolean, default: false }, // Flag for auto-generated groups
  groupType: { 
    type: String, 
    enum: ['admin', 'faculty', 'batch'], 
    default: 'admin' 
  }, // Type of group: admin, faculty, or batch
  moduleInfo: { // Information about the modules this group is based on
    startTiming: { type: String },
    endTiming: { type: String },
    branchName: { type: String },
    facultyName: { type: String }, // Single faculty name
    modules: [{ type: String }] // Array of module names
  }
}, {
  timestamps: true // createdAt, updatedAt
});

module.exports = mongoose.model('Group', GroupSchema); 