export const STUDENT_RESPONSES = [
  'Call Not Picked',
  'Switch Off',
  'Call Back',
  'Incoming Off',
  'Invalid Number',
  'Network Issue',
  'Wrong Number',
  'Discuss with Parents',
  'Parents Are Not Available',
  'Parents Denied',
  'Student Not Available',
  'Not Searching Course',
  'Not Interested',
  'Interested',
  'Will Confirm',
  'After Exam',
  'Out of Delhi',
  'Visit Tomorrow',
  'Visit in a Few Days',
  'Location Is Faar',
];

export const BRANCH_OPTIONS = [
  'Badarpur',
  'Kalkaji',
];

export const SOURCE_OPTIONS = [
  'Board-Banner-Brochure',
  'DTSE',
  'DM',
  'GMB',
  'Indoor',
  'SOL',
  'Other Reference',
  'Student Reference',
  'Web Lead',
  'Whatsapp API-Brodcast',
  'Whatsapp API-Web',
  'Update Course',
  'Google IVR',
  'Double Tick',
];

export const COURSE_OPTIONS = [
'A-Level',
'ADCA',
'Advance Diploma In Digital Marketing',
'Advance Diploma In Full Stack Web Development',
'Advance Diploma In Financial Market',
'Advance Excel',
'Advanced Digital Marketing',
'Advanced Java Course',
'Advanced Python',
'Affiliate Marketing',
'Animation 2D & 3D',
'AUTOCAD',
'Back End Development',
'Basic Computer',
'Basic Stock Market',
'Business Analyst',
'C Language',
'C++ Course',
'CCC',
'Comprehensive Diploma In science and AI',
'Certification in Digital Marketing',
'Certification Data Analyst and Visualization',
'Certification Hardware Engineering',
'Certification in Ethical Hacking With Python',
'Certification in Financial Accounting',
'Certification in Professional Accounting',
'Core Java Courses',
'Core Python Course',
'Corporate E-Accounting',
'CPC',
'CCOA',
'Cyber Security & Ethical Hacking',
'Cyber Security and Web Pentesting',
'ChatGPT',
'Data Entry Operator',
'Data Science',
'DCA',
'DMA',
'DCAP',
'Desktop Publishing',
'Diploma in Digital Marketing',
'Diploma in Digital Marketing and Web Development',
'Diploma In Financial Market',
'Diploma in Hardware & Networking',
'Diploma in Programming Course (DIP)',
'Diploma in Web and app Development',
'Diploma in Software Engineering',
'Diploma in Stock Market',
'Diploma in It Infra and Management',
'Front End Development',
'FULL STACK DEVELOPMENT COURSE',
'Full Stack Mobile App Development',
'Forex',
'Google Ads',
'Graphic Design',
'Graphic Design Pro',
'GST Course Content',
'Income Tax',
'Interior Design',
'IT-GENIUS',
'Mobile App Development using Flutter',
'Mobile App Development using Java',
'Mobile App Development using React Native',
'Master in Web Development & App Development',
'Master in Data Analysis and Visualization',
'Master in Digital Marketing',
'Mern Stack Development Course',
'Motion Graphic',
'MDMA',
'MIS',
'NCFM Capital Market',
'NCFM Option Strategies',
'NCFM Techinal Analysis',
'NISM Commodity Derivative',
'NISM Currency Derivative',
'NISM Derivative Series VIII',
'O-Level',
'Penetration Testing Course',
'Professional Stock Market',
'Professional In Data Analysis',
'Social Media Marketing',
'Spoken English',
'Seo',
'Tally E-Accounting',
'Tally Essential 1',
'Tally Essential 2',
'Tally Taxation Essentials',
'Typing',
'TDL',
'TDS',
'UI/UX Design',
'Video Editing',
'Website Designing and Development',
'Web Design & Development',
'Web Design',
'Wordpress Course',
];

export const LEAD_STATUS_OPTIONS = ['Hot', 'Warm', 'Cold'];
